apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-watchlist-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-watchlist-service
            port:
              number: 80
