apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-watchlist
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: flask-watchlist
  template:
    metadata:
      labels:
        app: flask-watchlist
    spec:
      containers:
      - name: flask-watchlist
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
