apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: flask-watchlist
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.domain }}`)
      kind: Rule
      services:
        - name: flask-watchlist-service
          port: 80
  tls:
    certResolver: myresolver
