apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  labels:
    {{- include "flask-watchlist.commonLabels" . | nindent 4 }}
spec:
  selector:
    {{- include "flask-watchlist.selectorLabels" . | nindent 4 }}
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http
